// AUTOGENERATED by scripts/sync-bookings.mjs at build time, sourced from
// the Google Calendar iCal feed at BOOKINGS_ICAL_URL.
//
// Edits below survive locally for testing, but are overwritten by the next
// CI build. Permanent bookings should live in the calendar.
export const bookedDates: readonly string[] = [
];
